### ISSUE TITLE
Selecionar as imagens para este projeto

### ISSUE THREAD

**Issue by emmanuelmarcosdeoliveira** [emmanuelmarcosdeoliveira/verificador-de-idade#1]

**Comment by emmanuelmarcosdeoliveira** [comment]
## Por favor fazer a seleção das imagens e colocar no projeto.

**Comment by oliveira-emmanuel** [comment]
Ok irei providenciar as imagens

**Comment by oliveira-emmanuel** [comment]
Já foi feito a seleção das imagens e foi adicionado ao projeto @emmanuelmarcosdeoliveira
